### PR TITLE
Feat(4as): 4as modal, affected population display, legend and pagination

### PR DESCRIPTION
**Pull request by kennethliporada**
# Description
- Title Freeze Header
- hide and show affected data
- Population Affected display (color pink)
- Use new api from backend to test data
- Add “%” in column for Percentage Affected
- Add “.” decimal and “,” comma in column for Total Population, Total Affected Population, Affected to Med-Hign column in modal display

### CODE REVIEW

**Comment by kennethliporada** [comment]
# Description
- display affected data population with match the Bgy_Code to the affected_psgc

# Screenshot
image

**Comment by kennethliporada** [comment]
# Description
- edited a legend for rain forecast
- added a "Low" for legend Exposure Population
- Added a value VAR 1 for map display Affected Population


# Screenshot
image

image

**Comment by kennethliporada** [comment]
# Description
- added a pagination for the table
- displaying barangay data from ngrok
- 20 brgy per page

# Screenshot
image

**Comment by kennethliporada** [comment]
# Description
- added number of data in pagination

# Screenshot
image

**Comment by kennethliporada** [comment]
# Description
- added a search not only for barangay but also the muni, prov and etc...
- added a notification just in case no data or API problem

# Screenshot

image

**Comment by kennethliporada** [comment]
# Description
- added a toggle legend for exposure population
- changing legend exposure population
- rain forecast display in map


# Screenshot
image

image

**Comment by kennethliporada** [comment]
# Description
- changing legend font style for Population Exposure
- fixed bug for pagination 
- changing url for rain forecast
- added a disable cursor for next and previous button

# Screenshots
image

image

**Comment by kennethliporada** [comment]
# Description
- Font sizes calculate risk and "No data Available" bigger

**Comment by kennethliporada** [comment]
# Description
- fix pagination for modal 4as summary
- added a disclaimer

# Screenshots
image

**Comment by kennethliporada** [comment]
# Description
- inserted beta to the risk assessment sidebar 
- remove Data summary button and replace it to the map component
- replace 4as data summary button to the map component
- remain checked when sidebar is toggle
- created a function to stay checked the checkbox population
- added a boolean shown to population checkbox
- fix bug about the checkbox population

# Screenshot
image

image

**Comment by kennethliporada** [comment]
# Description 
- fix bug button for calculate risk when toggle sidebar

**Comment by kennethliporada** [comment]
# Description
- added a opacity to the rain forecast and to the population affected

# Loom
https://www.loom.com/share/6df109b1f55a4ace8794a35d2bc7e784?sid=bcd703a7-ee6b-4e70-b532-d45f95fe98fb

**Review by bon-carpo — APPROVED** [review]

**Pull request merged**
