### PR TITLE
feat(qc-studio): Graph/Chart with Calendar module

### PR DESCRIPTION
**Pull request by kennethliporada**
# Description 
- added calendar in data graph

# Notes
- data about `pointStart` is static only

# Screenshot
image

image

### CODE REVIEW

**Comment by kennethliporada** [comment]
# Description
- created shared module for disclaimer and working
- created shared module for view summary not ye working
-

# Screenshot
image|

# Loom
https://www.loom.com/share/2d9dcdf9116748529960f369a967f5c3

**Comment by kennethliporada** [comment]
# Description
- (for trial) change date and time to whole number (milliseconds)
- Still spike for highstock/calendar

# Error
- calendar dont have value from api

**Comment by kennethliporada** [comment]
# Description
- Changed sidebar iot name
- iot calendar with data from api

# Screenshot
- IoT Sidebar name
image

- to follow the iot graph because i dont have baseurl for now

**Comment by kennethliporada** [comment]
# Description
- Iot disclaimer with cpntent

# Screenshot
image

**Review by bon-carpo — APPROVED** [review]
### Show Graph/Chart with Calendar module

**Pull request merged**
