### PR TITLE
WIP: feat(studio): add options with opacity for weather satellite component

### PR DESCRIPTION
**Pull request by bon-carpo**
### To do's:
---
- [x]  Create state in store
- [x]  Create initial value
- [x]  Create weather services in playground
- [x]  Toggle weather satellite layer default himawari
- [x]  Expand weather satellite
- [x]  Can toggle layers from himawari to himawari-gsmap
- [x]  Change url link for himawari and gsmap 
- [x]  Can change opacity for Himawari
- [ ]  Can change opacity for GSMAP

### Screenshots/Recordings
---
NOTE:  No video images output 
https://www.loom.com/share/6701bf09155c467ab8b6b49dc1f666a6

## Before
---
NOTE: Can set opacity but not changing in the map.
https://www.loom.com/share/ec5bc4c831dc4243a343bf4ee5b99e19

## Updates as of 11.18.2021
---
NOTE: Can change opacity for Himawari only
https://www.loom.com/share/ae05bee14e5d45c9953bb5283cd9d1c1

## Latest updates as of 11.23.2021
---
NOTE: Can change opacity for Himawari only but can toggle layers between himawari and GSMAP(see loom recordings)
https://www.loom.com/share/d94062413d7c4409b1ba4376303915bf

ERROR: Selected Himawari-GSMAP but in Change State shown is still "False"
image

### CODE REVIEW

**Comment by jadurani** [comment]
Resolve conflicts please

image

**Comment by bon-carpo** [comment]
Resolved conflicts na po :)

**Comment by jadurani** [comment]
Hi @bon-carpo, where are the technical notes that I've asked weeks ago? This is for **your** debugging purposes.

**Comment by jadurani** [comment]
Fixed here: 

Kapture 2021-12-01 at 04 06 51

Let's discuss later how it was fixed

**Comment by bon-carpo** [comment]
### Steps for weather satellite add options and opacity
---
## noah-playground.store.ts
- created array for weather satellite type and export as const
- created WeatherSatelliteState with property as follows:	
```
 export type WeatherSatelliteState = {
      shown: boolean;
      expanded: boolean;
      selectedType: WeatherSatelliteType;
      types: WeatherSatelliteTypesState;
   };
```
```
 export type WeatherSatelliteTypesState = {
      himawari: WeatherSatelliteTypeState;
      'himawari-GSMAP': WeatherSatelliteTypeState;
   };
```
```
export type WeatherSatelliteTypeState = {
      opacity: number;
      shown: boolean;
   };
```
- created initial value in NoahPlaygroundState
 ```
weatherSatellite: {
    shown: false,
    expanded: false,
    selectedType: 'himawari',
    types: {
      himawari: {
        shown: true,
        opacity: 30,
      },
      'himawari-GSMAP': {
        shown: false,
        opacity: 50,
      },
    },
  },
```

## noah-playground.service.ts
- import WeatherSatelliteState, WeatherSatelliteType, WeatherSatelliteTypeState from store
- created observable for shown, expanded and selectedType
- created getter and setter for opacity

## weather-satellite-playground component
- created to toggle visibility and expansion

## weather component
- created to show weather satellite options and opacity

## map-playground component
- created initWeatherSatelliteLayers functions
```
 initWeatherSatelliteLayers() {
    WEATHER_SATELLITE_ARR.forEach((ws) => this._loadWeatherSatellite(ws));
   }
```
- add details/source per weather satellite type
```
  this.map.addSource(
        weatherType,
        getWeatherSatelliteSource(weatherSatelliteDetails)
      );

```
- add layer per weather satellite source
 ```
 this.map.addLayer({
        id: weatherType,
        type: 'raster',
        source: weatherType,
        paint: {
          'raster-fade-duration': 0,
          'raster-opacity': 0,
        },
      });
```

- for opacity
 ```
     const weatherOp$ = this.pgService
        .getWeatherSatellite$(name)
        .pipe(distinctUntilChanged((x, y) => x.opacity !== y.opacity));

      combineLatest([allShown$, weatherOp$])
        .pipe(takeUntil(this._unsub), takeUntil(this._changeStyle))
        .subscribe(([allShown, weatherOp]) => {
          let newOpacity = 0;

          if (weatherOp.opacity && allShown) {
            newOpacity = weatherOp.opacity / 100;
          }
          this.map.setPaintProperty(name, 'raster-opacity', newOpacity);
        });
```

- for shown
 ```
   const weather$ = this.pgService
        .getWeatherSatellite$(name)
        .pipe(distinctUntilChanged((x, y) => x.shown !== y.shown));

      combineLatest([allShown$, weather$])
        .pipe(takeUntil(this._unsub), takeUntil(this._changeStyle))
        .subscribe(([allShown, weather]) => {
          let newOpacity = 0;

          if (weather.shown && allShown) {
            newOpacity = weather.opacity / 100;
          }

          this.map.setPaintProperty(name, 'raster-opacity', newOpacity);
        });
    });
```

**Pull request merged**
